### ISSUE TITLE
not working with me

### ISSUE THREAD

**Issue by betapcode** [digitaldrummerj-ionic/ionic-local-notifications-sample#1]
i have run app on ios
$ ionic build ios
open xcode => build => on iphone
and i saw error log
 error    Error: n.cordova is undefined
.schedule@http://172.16.2.5:8100/lib/ngCordova/dist/ng-cordova.min.js:8:28309
$scope.scheduleInstantNotification@http://172.16.2.5:8100/js/app.js:49:5

Please helpe me, thanks !

**Comment by digitaldrummerj** [comment]
It sounds like the local notification plugin is not installed.  After you pulled down the code did you run the command "ionic state restore"?  This command will add back platforms and any cordova plugin listed in the package.json file.

**Comment by betapcode** [comment]
I have run command step by step : 
cd ionic-local-notifications-sample
npm install
bower install
ionic state restore
and 
ionic build ios 
=> but not working

**Comment by betapcode** [comment]
I used Macbook OSX Yosemite 10.10.5
- ionic version : 1.7.12
- cordova version : 5.4.1

**Comment by betapcode** [comment]
if i move "lib/ngCordova/dist/ng-cordova.min.js"
change:
  lib/ngCordova/dist/ng-cordova.js
then i saw error : 
Error: $window.cordova is undefined
.schedule@http://172.16.2.5:8100/lib/ngCordova/dist/ng-cordova.js:4756:9

**Comment by digitaldrummerj** [comment]
There is no iOS platform add in this sample project.  When you try to run ionic build ios you should have gotten an error that ios is not added as a platform.  Not sure where the error you are getting is coming from.  If you are trying to compile this in XCode directly then that is causing you the issues.  

To add iOS as a platform run:

```
ionic platform add ios
```

Then you should be able to build for iOS if everything is setup on your machine correctly. 

```
ionic build ios
```

**Comment by betapcode** [comment]
it's ok , thanks :+1:
